services:
  app-stable:
    image: ghcr.io/aryan20apr/springboot-cicd:${STABLE_TAG:-latest}
    container_name: app-stable
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s
    networks:
      - app-net

  app-canary:
    image: ghcr.io/aryan20apr/springboot-cicd:${CANARY_TAG:-latest}
    container_name: app-canary
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./canary.conf:/etc/nginx/conf.d/canary.conf
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
