resolver 127.0.0.11 valid=10s;

server {
    listen 80;

    set $upstream_app app;

    location / {
        proxy_pass http://$upstream_app:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /actuator/health {
        proxy_pass http://$upstream_app:8080/actuator/health;
    }
}