server:
  port: 8080

logging:
  level:
    root: WARN
    '[com.example.cicddemo]': INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoint:
    health:
      show-details: never